= Getting Involved

There are a variety of ways to get involved and seek help if and when
you need it. Here’s the best ways.

[[mailing-lists]]
== Mailing lists

On the https://mailman.owncloud.org[mailing lists].

[[community-support-forum]]
== Community support forum

Ask questions on http://central.owncloud.org/[ownCloud Central]. We
strongly recommend using ownCloud Central, as it hosts dedicated FAQ
pages. These include topics which address typical mistakes and commonly
occurring issues.

[[social-media]]
== Social media

Ask questions on social media.

* https://plus.google.com/+ownclouders/[Google Plus]
* https://www.facebook.com/ownclouders/[Facebook]
* https://twitter.com/ownclouders/[Twitter]

[[irc-channels]]
== IRC channels

Chat with us on http://www.irchelp.org/[IRC] (*irc.freenode.net*). You
can chat via the web with http://webchat.freenode.net, or use your
favorite IRC client. The channel names are:

* Setup: *#owncloud*
* Testing: *#owncloud-testing*
* Development: *#owncloud-dev*
* Design: *#owncloud-design*

[[maintainers]]
== Maintainers

If you need to contact a maintainer of a certain app or division you can
find the details at https://owncloud.org/contact/.
