Desktop and Mobile Synchronization
==================================

For synchronizing files with your desktop computer, we recommend using
the https://owncloud.org/sync-client/[ownCloud Sync Client] for Windows,
Mac OS X and Linux.

The ownCloud Desktop Sync Client enables you to connect to your private
ownCloud Server. You can create folders in your home directory, and keep
the contents of those folders synced with your ownCloud server. Simply
copy a file into the directory and the ownCloud desktop client does the
rest. Make a change to the files on one computer, it will flow across
the others using these desktop sync clients. You will always have your
latest files with you wherever you are.

Its usage is documented separately in the
https://doc.owncloud.com/desktop/latest/[ownCloud Desktop Client
Manual].

[[mobile-clients]]
Mobile Clients
--------------

Visit your Personal page in your ownCloud Web interface to find download
links for Android and iOS mobile sync clients. Or, visit the
https://owncloud.org/install/[ownCloud download page].

Visit the https://doc.owncloud.org/[ownCloud documentation page] to read
the mobile apps user manuals.
