= Upgrade Marketplace Applications

To upgrade Marketplace applications, please refer to the documentation
below, as applicable for your ownCloud setup.

[[single-server-environment]]
Single-Server Environment
-------------------------

To upgrade Marketplace applications when running ownCloud in a single server environment, you can use use xref:configuration/server/occ_command.adoc#apps-commands[the Market app], specifically by running `market:upgrade`. 
This will install new versions of your installed apps if updates are available in the marketplace.

NOTE: The user running the update command, which will likely be your webserver user, needs write permission for the `/apps` folder. If they don’t have write permission, the command may report that the update was successful, however it may silently fail.

[[clusteredmulti-server-environment]]
Clustered/Multi-Server Environment
----------------------------------

The Market app <market_commands_label>, both the UI and command line,
are not, _currently_, designed to operate on clustered installations.
Given that, you will have to update the applications on each server in
the cluster individually. There are several ways to do this. But here is
a concise approach:

1.  Download the latest server release (whether
https://download.owncloud.org/community/owncloud-10.0.4.tar.bz2[the
tarball] or
https://download.owncloud.org/community/owncloud-10.0.4.zip[the zip
archive]).
2.  Download your installed apps from the ownCloud marketplace.
3.  Combine them together into one installation source, such as _a
Docker or VM image_, or _an Ansible script_, etc.
4.  Apply the combined upgrade across all the cluster nodes in your
ownCloud setup.
