= Android Application Development

ownCloud provides an official ownCloud Android client, which gives its
users access to their files on their ownCloud. It also includes
functionality like automatically uploading pictures and videos to
ownCloud. For third party application developers, ownCloud offers the
ownCloud Android library under the MIT license.

[[android-owncloud-client-development]]
== Android ownCloud Client development

If you are interested in working on the ownCloud android client, you can find the source code https://github.com/owncloud/android/[in github].
The setup and process of contribution is https://github.com/owncloud/android/blob/master/SETUP.md[documented here]. 
You might want to start with doing one or two https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+label%3A%22Junior+Job%22[junior jobs] to get into the code and note our xref:general/codingguidelines.adoc[General Contributor Guidelines]. 
Note that contribution to the Android client require signing the https://owncloud.org/contribute/agreement/[ownCloud Contributor Agreement].

[[owncloud-android-library]]
== ownCloud Android Library

This document will describe how to the use ownCloud Android Library. The
ownCloud Android Library allows a developer to communicate with any
ownCloud server; among the features included are file synchronization,
upload and download of files, delete rename files and folders, etc.

This library may be added to a project and seamlessly integrates any
application with ownCloud. The tool needed is any IDE for Android. This
guide includes some screenshots showing examples in Eclipse.
