= External API

[[introduction]]
== Introduction

The external API inside ownCloud allows third party developers to access
data provided by ownCloud apps. ownCloud follows the
http://www.freedesktop.org/wiki/Specifications/open-collaboration-services-1.7[OCS
v1.7 specification] (draft).

[[usage]]
== Usage

[[registering-methods]]
=== Registering Methods

Methods are registered inside the appinfo/routes.php using :phpOCP\\API

[source,php]
----
<?php

\OCP\API::register(
    'get', 
    '/apps/yourapp/url', 
    function($urlParameters) {
      return new \OC_OCS_Result($data);
    },
    'yourapp', 
    \OC_API::ADMIN_AUTH
);
----

[[returning-data]]
=== Returning Data

Once the API backend has matched your URL, your callable function as
defined in *$action* will be executed. This method is passed as array of
parameters that you defined in *$url*. To return data back the the
client, you should return an instance of :phpOC_OCS_Result. The API
backend will then use this to construct the XML or JSON response.

[[authentication-basics]]
Authentication & Basics
~~~~~~~~~~~~~~~~~~~~~~~

Because REST is stateless you have to send user and password each time
you access the API. Therefore running ownCloud *with SSL is highly
recommended* otherwise *everyone in your network can log your
credentials*:

....
https://user:password@yourowncloud.com/ocs/v1.php/apps/yourapp
....

[[output]]
=== Output

The output defaults to XML. If you want to get JSON append this to the
URL:

....
?format=json
....

Output from the application is wrapped inside a *data* element:

*XML*:

[source,xml]
----
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
   <!-- data here -->
 </data>
</ocs>
----

*JSON*:

[source,js]
----
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 100,
      "message": null
    },
    "data": {
      // data here
    }
  }
}
----

[[statuscodes]]
=== Statuscodes

The statuscode can be any of the following numbers:

* *100* - successful
* *996* - server error
* *997* - not authorized
* *998* - not found
* *999* - unknown error
