User Interface Testing
======================

[[requirements]]
Requirements
------------

* ownCloud >= 10.0. Make sure you have a running instance of ownCloud
https://doc.owncloud.com/server/latest/admin_manual/installation/[completely
setup].
* Default language set to `en` (in `config/config.php` set
`'default_language' => 'en',`).
* An admin user called `admin` with the password `admin`.
* No self-signed SSL certificates.
* Testing utils (running `make` in your terminal from the `webroot` directory will install them).
* link:https://docs.docker.com/install/linux/docker-ce/ubuntu/[Docker CE Installed]
* link:https://docs.docker.com/install/linux/linux-postinstall/[Docker Post-install] done to put your developer account in the docker group so you can run Docker without `sudo`
* Docker subnet enabled for any firewall that may be active such as, link:https://help.ubuntu.com/community/UFW[ufw]. The example below shows how to update ufw's firewall rules to allow the `172.17.0.0/16` Docker subnet:

  sudo ufw status
  sudo ufw allow from 172.17.0.0/16


* Docker containers pulled. It is recommended to use `standalone-chrome-debug` which allows seeing the browser live. 
You will also need link:https://github.com/mailhog/MailHog[MailHog]. 
Pull any or all of these Docker containers:

[source]
----
docker pull selenium/standalone-chrome
docker pull selenium/standalone-chrome-debug
docker pull selenium/standalone-firefox
docker pull selenium/standalone-firefox-debug
docker pull mailhog/mailhog
----

* A `vnc` viewer installed (in order to view the browser action as the UI tests run). For example:

[source]
----
sudo apt install tigervnc-viewer
----

* To run the link:https://www.seleniumhq.org[Selenium server] locally (not in Docker) see the notes at the end.

[[overview]]
Overview
--------

Tests are divided into suites, enabling each suite to test some logical portion of the functionality and for the total elapsed run-time of a single suite to be reasonable (up to about 40 minutes on Travis-CI, about 10 minutes on drone).
Elapsed run-time on a local developer system is very dependent on the IO as well as CPU performance.
Smaller apps may have all tests in a single suite.

Each suite consists of a number of features. Each feature is described
in a `*.feature` file. There are a number of scenarios in each feature
file. Each scenario has a number of scenario steps that define the steps
taken to do the test.

[[set-up-test]]
Set Up Test
-----------

- Start the Selenium Docker container in a terminal:

[source,console]
----
docker run -p 4445:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug
----

Ports on the Selenium Docker IP address are mapped to `localhost` so they can be accessed by the tests and the `vnc` viewer.

* Start the MailHog Docker container in another terminal:

[source]
----
docker run -p 1025:1025 -p 8025:8025 mailhog/mailhog
----

Ports on the MailHog docker IP address are mapped to `localhost` so they can be accessed by the tests.
By running these in terminal windows, it is simple to press `ctrl-C` to stop them when you are finished.

* Set the following environment variables:
** `SRV_HOST_NAME` (The hostname where ownCloud runs)
** `REMOTE_FED_SRV_HOST_NAME` (An alternative hostname for federation
share tests. This should be another IP/hostname on the same server)
** `SRV_HOST_URL` (The path, if ownCloud does not run in the root of the
host)
** `REMOTE_FED_SRV_HOST_URL` (The path, if the alternative ownCloud for
federation share tests does not run in the root of the host)
** `SRV_HOST_PORT` (The port of your webserver)
** `REMOTE_FED_SRV_HOST_PORT` (The alternative port of your webserver
for federation share tests. This should be another port on the same
server)
** `BROWSER` (Any one of `chrome`, `firefox`, `internet explorer`)
** `BROWSER_VERSION` (version of the browser you want to use - _optional_)
+
e.g., to test an instance running on the Docker subnet with Chrome do:
+
[source,console]
----
export SRV_HOST_NAME=172.17.0.1
export REMOTE_FED_SRV_HOST_NAME=172.17.0.1
export SRV_HOST_URL=owncloud-core
export REMOTE_FED_SRV_HOST_URL=owncloud-core
export SRV_HOST_PORT=8080
export REMOTE_FED_SRV_HOST_PORT=8180
export BROWSER=chrome
----

* If your ownCloud install is running locally on Apache, then it should already be available on the Docker  subnet at `172.17.0.1`

* If you don’t have a webserver already running, leave SRV_HOST_URL
empty ( `export SRV_HOST_URL=""` ), and start the PHP development server
with:
 
[source,console]
----
bash tests/travis/start_php_dev_server.sh
----

The server will bind to: `$SRV_HOST_NAME:$SRV_HOST_PORT`.

* To run the federation Sharing tests:
1.  Make sure you have configured HTTPS with valid certificates on both
servers URLs
2.  https://doc.owncloud.org/server/latest/admin_manual/configuration/server/import_ssl_cert.html[Import
SSL certificates] (or do not offer HTTPS).
* Run a suite of tests:
+
[source,console]
----
bash tests/travis/start_ui_tests.sh --suite webUILogin
----

The names of suites are found in the `tests/acceptance/config/behat.yml` file, and start with `webUI`.
The tests need to be run as the same user who is running the webserver and this user must be also owner of the config file (`config/config.php`).
To run the tests as a user that is different to your current terminal user run `sudo -E -u <username>`. For example, to execute the script as as `www-data`, run `sudo -E -u www-data bash tests/travis/start_ui_tests.sh`.

* The browser for the tests runs inside the Selenium docker container. View it by running the `vnc` viewer: `vncviewer`.

And connect to `localhost`. The VNC password of the docker container is `secret`.

[[running-ui-tests-using-ipv6]]
Running UI Tests using IPv6
---------------------------

The test system must have (at least locally) functioning IPv6:

* working loopback address ::1
* a `real` routable IPv6 address (not just a link-local address)

If you have a server set up that listens on both IPv4 and IPv6 (e.g. localhost on 127.0.0.1 and ::1) then the UI tests will access the server via whichever protocol your operating system prefers.
If there are tests that specifically specify IPv4 or IPv6, then those will choose a suitable local address to come from so that they access the server using the required IP version.

If you are using the PHP dev server, then before starting it, in addition to the exports in the Set Up Test section, specify where the IPv6 server should listen:

[source,console]
----
export IPV6_HOST_NAME=ip6-localhost
----

Then both IPv4 and IPv6 PHP dev servers will be started by the script:

[source,console]
----
bash tests/travis/start_php_dev_server.sh
----

If you want the tests to drive the UI over IPv6, then export an IPv6
name or address for `SRV_HOST_NAME` and an IPv4 name or address for
`IPV4_HOST_NAME`:

[source,console]
----
export SRV_HOST_NAME=ip6-localhost
export IPV4_HOST_NAME=localhost
----

Because not everyone will have functional IPv6 on their test system yet, tests that specifically require IPv6 are tagged `@skip @ipv6`. 
To run those tests, follow the section below on running skipped tests and specify `--tags @ipv6`.

[[running-ui-tests-for-one-feature]]
Running UI Tests for One Feature
--------------------------------

You can run the UI tests for just a single feature by specifying the
feature file:

[source,console]
----
bash tests/travis/start_ui_tests.sh \
  --feature tests/acceptance/features/webUITrashbin/trashbinDelete.feature
----

To run just a single scenario within a feature, specify the line number
of the scenario:

[source,console]
----
bash tests/travis/start_ui_tests.sh 
  --feature tests/acceptance/features/webUITrashbin/trashbinDelete.feature:<linenumber>
----

[[running-ui-tests-for-an-app]]
Running UI Tests for an App
---------------------------

With the app installed, run the UI tests for the app by specifying the
location of the app’s `behat.yml` config file:

[source,console]
----
bash tests/travis/start_ui_tests.sh \
  --config apps/files_texteditor/tests/acceptance/config/behat.yml \
  --suite webUITextEditor
----

Run UI the tests for just a single feature of the app by also specifying
the feature file:

[source,console]
----
bash tests/travis/start_ui_tests.sh \
  --config apps/files_texteditor/tests/acceptance/config/behat.yml \
  --feature apps/files_texteditor/tests/acceptance/features/webUITextEditor/editTextFiles.feature
----

[[skipping-tests]]
Skipping Tests
--------------

If a UI test is known to fail because of an existing bug, then it is
left in the test set _but_ is skipped by default. Skip a test by tagging
it `@skip` and then put another tag with text that describes the reason
it is skipped. e.g.,:

[source,console]
----
@skip @quota-should-not-be-set-to-invalid-values-issue-1234
Scenario Outline: change quota to an invalid value
----

Skipped tests are listed at the end of a default UI test run. 
You can locally run the skipped test(s). 
Run all skipped tests with:

[source,console]
----
bash tests/travis/start_ui_tests.sh --tags @skip
----

Or run just a particular test by using its unique tag:

[source,console]
----
bash tests/travis/start_ui_tests.sh 
  --tags @quota-should-not-be-set-to-invalid-values-issue-1234
----

When fixing the bug, remove these skip tags in the PR along with the bug
fix code.

=== Additional Command Options

Running all test suites in a single run is not recommended. 
It will take more than 1 hour on a typical development system.
However, you may run all UI tests with:

[source]
----
bash tests/travis/start_ui_tests.sh --all-suites
----

By default, any test scenarios that fail are automatically rerun once. 
This minimizes transient failures caused by browser and Selenium driver timing issues.
When developing tests it can be convenient to override this behavior.

To not rerun failed test scenarios:

[source]
----
bash tests/travis/start_ui_tests.sh \
  --norerun \
  --suite webUILogin
----

=== Local Selenium Setup

You may optionally run the Selenium server locally.
Docker is now the recommended way, but local Selenium is also possible:

* `Selenium standalone server <http://docs.seleniumhq.org/download/>`_ e.g. version 3.12.0 or newer.
* Browser installed that you would like to test on (e.g. chrome)
* `Web driver for the browser that you want to test <http://www.seleniumhq.org/download/#thirdPartyDrivers>`_.
* Place the Selenium standalone server jar file and the web driver(s) somewhere in the same folder.
* Start the Selenium server:

[source]
----
java -jar selenium-server-standalone-3.12.0.jar \
  -port 4445 \
  -enablePassThrough false
----

- In this configuration, the tests will continually open the browser-under-test on your local system.
- If you run any test scenarios that need MailHog (to test password reset etc.), then you need to run the MailHog Docker container. That is much simpler than trying to configure MailHog on your local system.



[[known-issues]]
Known Issues
------------

* Tests that are known not to work in specific browsers are tagged e.g., `@skipOnFIREFOX47+` or `@skipOnINTERNETEXPLORER` and will be skipped by the script automatically
* - The web driver for the current version of Firefox works differently to the old one. If you want to test FF < 56 you need to test on 47.0.2 and to use Selenium server 2.53.1 for it
- link:https://ftp.mozilla.org/pub/firefox/releases/47.0.2/[Download and install version 47.0.2 of Firefox].
- link:https://selenium-release.storage.googleapis.com/index.html?path=2.53/[Download version 2.53.2 of the Selenium web driver].
