Restoring ownCloud
==================

When you install ownCloud from packages, follow these steps to restore
your ownCloud installation. Start with a fresh ownCloud package
installation in a new, empty directory. Then restore these items from
your backup (see backup):

1.  Your `config/` directory.
2.  Your `data/` directory.
3.  Your ownCloud database.
4.  Your custom theme files, if you have any. (See https://doc.owncloud.org/server/latest/developer_manual/core/theming.html[Theming ownCloud])

When you install ownCloud from the source tarballs you may safely
restore your entire ownCloud installation from backup, with the
exception of your ownCloud database. Databases cannot be copied, but you
must use the database tools to make a correct restoration.

When you have completed your restoration, see xref:installation/source_installation.adoc#set-strong-directory-permissions[Set Strong Directory Permissions].

[[restore-directories]]
Restore Directories
-------------------

Simply copy your configuration and data folder to your ownCloud
environment. You could use this command, which restores the backup
example in backup:

....
rsync -Aax config data /var/www/owncloud/
....

There are many ways to restore normal files from backups, and you may
use whatever method you are accustomed to.

[[restore-database]]
Restore Database
----------------

NOTE: This guide assumes that your previous backup is called ``owncloud-dbbackup.bak``.

[[mysql]]
MySQL
~~~~~

MySQL is the recommended database engine. To restore MySQL:

....
mysql -h [server] -u [username] -p[password] [db_name] < owncloud-dbbackup.bak
....

[[sqlite]]
SQLite
~~~~~~

....
rm data/owncloud.db
sqlite3 data/owncloud.db < owncloud-dbbackup.bak
....

[[postgresql]]
PostgreSQL
~~~~~~~~~~

....
PGPASSWORD="password" pg_restore -c -d owncloud -h [server] -U [username] 
owncloud-dbbackup.bak
....
