= iOS Application Development

ownCloud provides an official ownCloud iOS client, which gives its users
access to their files on their ownCloud. It also includes functionality
like automatically uploading pictures and videos to ownCloud.

For third party application developers, ownCloud offers the ownCloud iOS
library under the MIT license.

[[ios-owncloud-client-development]]
== iOS ownCloud Client development

If you are interested in working on the ownCloud iOS client, you can
find the source code https://github.com/owncloud/ios[in github]. The
setup and process of contribution is
https://github.com/owncloud/ios/blob/master/SETUP.md[documented here].

You might want to start with doing one or two https://github.com/owncloud/ios/issues?q=is%3Aopen+is%3Aissue+label%3A%22Junior+Job%22[junior jobs] to get into the code and note our xref:general/codingguidelines.adoc[General Contributor Guidelines].

Note that contribution to the iOS client require signing the iOS addendum to the https://owncloud.org/contribute/agreement/[ownCloud Contributor Agreement]. 
You are permitted to test the iOS client on Apple hardware thanks to the https://owncloud.org/contribute/iOS-license-exception/[iOS license exception].

[[owncloud-ios-library]]
== ownCloud iOS Library

This document will describe how to the use ownCloud iOS library. The
ownCloud iOS library for iOS allows a developer to communicate with any
ownCloud server; among the features included are file synchronization,
upload and download of files, delete rename and move of files and
folders and share files or folders by link among others.

This library may be added to a project and seamlessly integrates any
application with ownCloud.

The tool needed is Xcode 6, this guide includes some screenshots showing
examples in Xcode 6.
