Linux Package Manager Installation
==================================

Package managers should only be used for single-server setups. For
production environments, we recommend installing from
https://owncloud.org/download/#owncloud-server-tar-ball[the tar
archive].

[[available-packages]]
Available Packages
------------------

The recommended package to use is `owncloud-files`. It only installs
ownCloud, and does not install Apache, a database, or any of the
required PHP dependencies.

[[installing-owncloud-community-edition]]
Installing ownCloud Community Edition
-------------------------------------

First, install your own LAMP stack, as doing so allows you to create
your own custom LAMP stack without dependency conflicts with the
ownCloud package. Then,
http://download.owncloud.org/download/repositories/10.0/owncloud/[update
package manager’s configuration].

Configurations are available for the following Linux distributions:

* Ubuntu 14.04 & 16.04
* Debian 7 & 8
* RHEL 6 & 7
* CentOS 7.2 & 7.3
* SLES 11SP4 & 12SP2
* openSUSE Leap 42.2 & 42.3

Repositories for Fedora, openSUSE Tumbleweed, and Ubuntu 15.04 have been
dropped. If you use Fedora, use
https://owncloud.org/download/#owncloud-server-tar-ball[the tar archive]
with your own LAMP stack. openSUSE users can rely on LEAP packages for
Tumbleweed.

Once your package manager has been updated, follow the rest of the
instructions on the download page to install ownCloud. Once ownCloud’s
installed, run xref:installation/installation_wizard.adoc[the Installation Wizard] to complete
your installation.

See the system_requirements for the recommended ownCloud setup and
supported platforms.

Do not move the folders provided by these packages after the
installation, as this will break updates.

[[what-is-the-correct-version]]
What is the Correct Version?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Package versions are composed of a major, a minor, and a patch number,
such as 9.0, 9.1, 10.0, 10.0.1, and 10.0.2. The second number represents
a major release, and the third number represents a minor release.

[[major-releases]]
Major Releases
^^^^^^^^^^^^^^

If you want to follow either of the most recent major releases, then
substitute `version` with either 9.0 or 10.0.

[[minor-releases]]
Minor Releases
^^^^^^^^^^^^^^

If you want to follow any of the four most recent patch releases, then
substitute `version` with one of 10.0.1, 10.0.2, 10.0.3, or 10.0.4.
Following a minor release avoids you accidentally upgrading to the next
major release before you’re ready.

[[the-latest-stable-version]]
The Latest Stable Version
^^^^^^^^^^^^^^^^^^^^^^^^^

Alternatively you can use `stable` for the latest stable version. If you
do, you never have to change it as it always tracks the current stable
ownCloud version through all major releases.

[[installing-owncloud-enterprise-edition]]
Installing ownCloud Enterprise Edition
--------------------------------------

See xref:enterprise/installation/install[the enterprise installation guide] for instructions on installing ownCloud Enterprise edition.

[[downgrading]]
Downgrading
-----------

Downgrading is not supported and risks corrupting your data! If you want
to revert to an older ownCloud version, install it from scratch and then
restore your data from backup. Before doing this, file a support ticket
(https://owncloud.com/pricing/[if you have paid support]) or ask for
help in the ownCloud forums to see if your issue can be resolved without
downgrading.

[[additional-guides-and-notes]]
Additional Guides and Notes
---------------------------

See installation_wizard for important steps, such as choosing the best
database and setting correct directory permissions. See
xref:installation/configuration_notes_and_tips.adoc#selinux[the SELinux guide] for a suggested configuration for SELinux-enabled distributions such as _Fedora_ and _CentOS_.

If your distribution is not listed, your Linux distribution may maintain
its own ownCloud packages or you may prefer to xref:installation/source_installation.adoc[install from source].

[[archlinux]]
Archlinux
~~~~~~~~~

The current
https://www.archlinux.org/packages/community/any/owncloud[stable
version] is in the official community repository, and more packages are
in the https://aur.archlinux.org/packages/?O=0&K=owncloud[Arch User
Repository].

[[mageia]]
Mageia
~~~~~~

The https://wiki.mageia.org/en/OwnCloud[Mageia Wiki] has a good page on
installing ownCloud from the Mageia software repository.

[[note-for-mysqlmariadb-environments]]
Note for MySQL/MariaDB environments
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Please refer to db-binlog-label on how to correctly configure your
environment if you have binary logging enabled.

[[running-owncloud-in-a-sub-directory]]
Running ownCloud in a sub-directory
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you’re running ownCloud in a sub-directory and want to use CalDAV or CardDAV clients, make sure you have configured the correct xref:issues/general_troubleshooting.adoc#service-discovery[service discovery URLs].
