Manual Installation on Linux
============================

Installing ownCloud on Linux from our Open Build Service packages is the
preferred method (see linux_installation). These are maintained by
ownCloud engineers, and you can use your package manager to keep your
ownCloud server up-to-date.

Enterprise customers should refer to ../enterprise/installation/install

If there are no packages for your Linux distribution, or you prefer
installing from the source tarball, you can setup ownCloud from scratch
using a classic LAMP stack (Linux, Apache, MySQL/MariaDB, PHP). This
document provides a complete walk-through for installing ownCloud on
Ubuntu 14.04 LTS Server with Apache and MariaDB, using
https://owncloud.org/install/[the ownCloud .tar archive].

* prerequisites_label
* ubuntu_installation_label
* apache_configuration_label
* enabling_ssl_label
* installation_wizard_label
* strong_perms_label
* selinux_tips_label
* php_ini_tips_label
* php_fpm_tips_label
* other_http_servers_label

Admins of SELinux-enabled distributions such as CentOS, Fedora, and Red
Hat Enterprise Linux may need to set new rules to enable installing
ownCloud. See selinux_tips_label for a suggested configuration.

[[prerequisites]]
Prerequisites
-------------

The ownCloud tar archive contains all of the required third-party PHP
libraries. As a result, no extra ones are, strictly, necessary. However,
ownCloud does require that PHP has a set of extensions installed,
enabled, and configured.

This section lists both the required and optional PHP extensions. If you
need further information about a particular extension, please consult
the relevant section of http://php.net/manual/en/extensions.php[the
extensions section of the PHP manual].

If you are using a Linux distribution, it should have packages for all
the required extensions. You can check the presence of a module by
typing `php -m | grep -i <module_name>`. If you get a result, the module
is present.

[[required]]
Required
~~~~~~~~

[[php-version]]
PHP Version
^^^^^^^^^^^

PHP >= 5.6 (ideally 7.0 or above)

[[php-extensions]]
PHP Extensions
^^^^^^^^^^^^^^

[width="100%",cols="28%,72%",options="header",]
|=======================================================================
|Name |Description
|https://secure.php.net/manual/en/book.ctype.php[Ctype] |For character
type checking

|https://php.net/manual/en/book.curl.php[cURL] |Used for aspects of HTTP
user authentication

|https://secure.php.net/manual/en/book.dom.php[DOM] |For operating on
XML documents through the DOM API

|https://php.net/manual/en/book.image.php[GD] |For creating and
manipulating image files in a variety of different image formats,
including GIF, PNG, JPEG, WBMP, and XPM.

|http://php.net/manual/en/function.hash.php[HASH Message]
http://php.net/manual/en/function.hash.php[Digest Framework] |For
working with message digests (hash).

|https://php.net/manual/en/book.iconv.php[iconv] |For working with the
iconv character set conversion facility.

|https://php.net/manual/en/book.intl.php[intl] |Increases language
translation performance and fixes sorting of non-ASCII characters

|https://php.net/manual/en/book.json.php[JSON] |For working with the
JSON data-interchange format.

|https://php.net/manual/en/book.libxml.php[libxml] |This is required for
the _https://secure.php.net/manual/en/book.dom.php[DOM],
_https://php.net/manual/en/book.libxml.php[libxml],
_https://php.net/manual/en/book.simplexml.php[SimpleXML], and
_https://php.net/manual/en/book.xmlwriter.php[XMLWriter] extensions to
work. It requires that libxml2, version 2.7.0 or higher, is installed.

|https://php.net/manual/en/book.mbstring.php[Multibyte String] |For
working with multibyte character encoding schemes.

|https://php.net/manual/en/book.openssl.php[OpenSSL] |For symmetric and
asymmetric encryption and decryption, PBKDF2, PKCS7, PKCS12, X509 and
other crypto operations.

|https://secure.php.net/manual/en/book.pdo.php[PDO] |This is required
for the pdo_msql function to work.

|https://secure.php.net/manual/en/book.phar.php[Phar] |For working with
PHP Archives (.phar files).

|https://php.net/manual/en/book.posix.php[POSIX] |For working with UNIX
POSIX functionality.

|https://php.net/manual/en/book.simplexml.php[SimpleXML] |For working
with XML files as objects.

|https://php.net/manual/en/book.xmlwriter.php[XMLWriter] |For generating
streams or files of XML data.

|https://php.net/manual/en/book.zip.php[Zip] |For reading and writing
ZIP compressed archives and the files inside them.

|https://php.net/manual/en/book.zlib.php[Zlib] |For reading and writing
gzip (.gz) compressed files.
|=======================================================================

The _Phar_, _OpenSSL_, and _cUrl_ extensions are mandatory if you want
to use https://www.gnu.org/software/make/[Make]
https://doc.owncloud.com/server/latest/developer_manual/general/devenv.html[to
setup your ownCloud environment], prior to running either the web
installation wizard, or the command line installer.

[[database-extensions]]
Database Extensions
^^^^^^^^^^^^^^^^^^^

[cols=",",options="header",]
|=======================================================================
|Name |Description
|https://secure.php.net/manual/en/ref.pdo-mysql.php[pdo_mysql] |For
working with MySQL & MariaDB.

|https://secure.php.net/manual/en/ref.pgsql.php[pgsql] |For working with
PostgreSQL. It requires PostgreSQL 9.0 or above.

|https://secure.php.net/manual/en/ref.sqlite.php[sqlite] |For working
with SQLite. It requires SQLite 3 or above. This is,

| |usually, not recommended, for performance reasons.
|=======================================================================

[[required-for-specific-apps]]
Required For Specific Apps
~~~~~~~~~~~~~~~~~~~~~~~~~~

[cols=",",options="header",]
|=======================================================================
|Name |Description
|https://secure.php.net/manual/en/book.ftp.php[ftp] |For working with
FTP storage

|https://secure.php.net/manual/de/book.ssh2.php[sftp] |For working with
SFTP storage

|https://secure.php.net/manual/en/book.imap.php[imap] |For IMAP
integration

|https://secure.php.net/manual/en/book.ldap.php[ldap] |For LDAP
integration

|https://pecl.php.net/package/smbclient[smbclient] |For SMB/CIFS
integration
|=======================================================================

SMB/Windows Network Drive mounts require the PHP module smbclient
version 0.8.0+; see

____________________________________________
../configuration/files/external_storage/smb.
____________________________________________

[[optional]]
Optional
~~~~~~~~

[cols=",",options="header",]
|=======================================================================
|Extension |Reason
|https://php.net/manual/en/book.bzip2.php[Bzip2] |Required for
extraction of applications

|https://php.net/manual/en/book.fileinfo.php[Fileinfo] |Highly
recommended, as it enhances file analysis performance

|https://php.net/manual/en/book.mcrypt.php[Mcrypt] |Increases file
encryption performance

|https://php.net/manual/en/book.openssl.php[OpenSSL] |Required for
accessing HTTPS resources

|https://secure.php.net/manual/en/book.imagick.php[imagick] |Required
for creating and modifying images and preview thumbnails
|=======================================================================

[[recommended]]
Recommended
~~~~~~~~~~~

[[for-specific-apps]]
For Specific Apps
^^^^^^^^^^^^^^^^^

[cols=",",options="header",]
|=======================================================================
|Extension |Reason
|https://php.net/manual/en/book.exif.php[Exif] |For image rotation in
the pictures app

|https://php.net/manual/en/book.gmp.php[GMP] |For working with
arbitrary-length integers
|=======================================================================

[[for-server-performance]]
For Server Performance
^^^^^^^^^^^^^^^^^^^^^^

For enhanced server performance consider installing one of the following
cache extensions:

* https://secure.php.net/manual/en/book.apcu.php[apcu]
* https://secure.php.net/manual/en/book.memcached.php[memcached]
* https://pecl.php.net/package/redis[redis] (>= 2.2.6+, required for
transactional file locking)

See ../configuration/server/caching_configuration to learn how to select
and configure a memcache.

[[for-preview-generation]]
For Preview Generation
^^^^^^^^^^^^^^^^^^^^^^

* https://libav.org/[avconv] or https://ffmpeg.org/[ffmpeg]
* https://www.openoffice.org/[OpenOffice] or
https://www.libreoffice.org/[LibreOffice]

[[for-command-line-processing]]
For Command Line Processing
^^^^^^^^^^^^^^^^^^^^^^^^^^^

[cols=",",options="header",]
|=======================================================================
|Extension |Reason
|https://secure.php.net/manual/en/book.pcntl.php[PCNTL] |Enables command
interruption by pressing `ctrl-c`
|=======================================================================

You don’t need the WebDAV module for your Web server (i.e. Apache’s
`mod_webdav`), as ownCloud has a built-in WebDAV server of its own,
http://sabre.io/[SabreDAV]. If `mod_webdav` is enabled you must disable
it for ownCloud. (See apache_configuration_label for an example
configuration.)

[[for-mysqlmariadb]]
For MySQL/MariaDB
~~~~~~~~~~~~~~~~~

The InnoDB storage engine is required, and MyISAM is not supported, see:
db-storage-engine-label.

[[install-the-required-packages]]
Install the Required Packages
-----------------------------

*When Are Stable Channel Packages Updated?*

Packages in the supported distributions’ stable channels are not
immediately updated following a release. This is because we need to make
sure that the release is sufficiently stable, as many people use
automatic updates. By waiting a number of business days after a tarball
has been released, we are able to make this assessment, based on a
number of criteria which include the submitted bug reports from systems
administrators.

[[on-ubuntu-16.04-lts-server]]
On Ubuntu 16.04 LTS Server
~~~~~~~~~~~~~~~~~~~~~~~~~~

On a machine running a pristine Ubuntu 16.04 LTS server, install the
required and recommended modules for a typical ownCloud installation,
using Apache and MariaDB, by issuing the following commands in a
terminal:

....
apt-get install -y apache2 mariadb-server libapache2-mod-php7.0 \
    openssl php-imagick php7.0-common php7.0-curl php7.0-gd \
    php7.0-imap php7.0-intl php7.0-json php7.0-ldap php7.0-mbstring \
    php7.0-mcrypt php7.0-mysql php7.0-pgsql php-smbclient php-ssh2 \
    php7.0-sqlite3 php7.0-xml php7.0-zip
....

*Please note:*

* `php7.0-common` provides: ftp, Phar, posix, iconv, ctype
* The Hash extension is available from PHP 5.1.2 by default
* `php7.0-xml` provides DOM, SimpleXML, XML, & XMLWriter
* `php7.0-zip` provides zlib

The remaining steps are analogous to the installation on Ubuntu 14.04 as
shown below.

[[on-ubuntu-14.04-lts-server]]
On Ubuntu 14.04 LTS Server
~~~~~~~~~~~~~~~~~~~~~~~~~~

On a machine running a pristine Ubuntu 14.04 LTS server, install the
required and recommended modules for a typical ownCloud installation,
using Apache and MariaDB, by issuing the following commands in a
terminal:

....
apt-get install -y wget expect apache2 mariadb-server libapache2-mod-php5 \
    libsmbclient-dev libssh2-1-dev openssl php5-imagick \
    php5-common php5-curl php5-dev php5-gd \
    php5-imap php5-intl php5-json php5-ldap \
    php5-mcrypt php5-mysql php5-pgsql php5-sqlite
....

*Please note:*

`libapache2-mod-php5` provides the following PHP extensions.

* ctype
* dom
* ftp
* hash
* iconv
* libxml
* mbstring
* openssl
* Phar
* posix
* SimpleXML
* xml
* xmlreader
* xmlwriter
* zip
* zlib

So if you don’t see an applicable package in the list above, that’s why.

[[installing-smbclient]]
Installing smbclient
^^^^^^^^^^^^^^^^^^^^

To install smbclient, you can use the following script. It first
installs PEAR, which at the time of writing only installs version 1.9.4.
However, smbclient requires version 1.9.5. So the final two commands
upgrade PEAR to version 1.9.5 and then install smbclient using Pecl.

....
#!/usr/bin/expect
spawn wget -O /tmp/go-pear.phar http://pear.php.net/go-pear.phar
expect eof

spawn php /tmp/go-pear.phar

expect "1-11, 'all' or Enter to continue:"
send "\r"
expect eof

spawn rm /tmp/go-pear.phar

pear install PEAR-1.9.5
pecl install smbclient
....

[[installing-ssh2]]
Installing ssh2
^^^^^^^^^^^^^^^

To install ssh2, which provides sftp, you can use the following command:

....
spawn pecl install ssh2
....

[[running-additional-apps]]
Running Additional Apps?
^^^^^^^^^^^^^^^^^^^^^^^^

If you are planning on running additional apps, keep in mind that you
might require additional packages. See prerequisites_label for details.

During the installation of the MySQL/MariaDB server, you will be
prompted to create a root password. Be sure to remember your password as
you will need it during ownCloud database setup.

[[additional-extensions]]
Additional Extensions
^^^^^^^^^^^^^^^^^^^^^

....
apt-get install -y php-apcu php-redis redis-server php7.0-ldap
....

[[rhel-redhat-enterprise-linux-7.2]]
RHEL (RedHat Enterprise Linux) 7.2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[required-extensions]]
Required Extensions
^^^^^^^^^^^^^^^^^^^

....
# Enable the RHEL Server 7 repository
subscription-manager repos --enable rhel-server-rhscl-7-eus-rpms

# Install the required packages
yum install httpd mariadb-server php55 php55-php \
  php55-php-gd php55-php-mbstring php55-php-mysqlnd
....

[[optional-extensions]]
Optional Extensions
^^^^^^^^^^^^^^^^^^^

....
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
  php-pecl-apcu redis php-pecl-redis php55-php-ldap
....

[[sles-suse-linux-enterprise-server-12]]
SLES (SUSE Linux Enterprise Server) 12
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[required-extensions-1]]
Required Extensions
^^^^^^^^^^^^^^^^^^^

....
zypper install apache2 apache2-mod_php5 php5-gd php5-json php5-curl \
  php5-intl php5-mcrypt php5-zip php5-zlib
....

[[optional-extensions-1]]
Optional Extensions
^^^^^^^^^^^^^^^^^^^

....
zypper install php5-ldap
....

[[apcu]]
APCu
++++

We are not aware of any officially supported APCu package for SLES 12.
However, if you want or need to install it, then we suggest the
following steps:

....
wget http://download.opensuse.org/repositories/server:/php:/extensions/SLE_12_SP1/ server:php:extensions.repo -O /etc/zypp/repos.d/memcached.repo 
zypper refresh
zypper install php5-APCu
....

[[redis]]
Redis
+++++

The latest versions of Redis servers have shown to be incompatible with
SLES 12. Therefore it is currently recommended to download and install
version 2.2.7 or a previous release from:
https://pecl.php.net/package/redis. Keep in mind that version 2.2.5 is
the minimum version which ownCloud supports.

[[install-owncloud]]
Install ownCloud
----------------

Now download the archive of the latest ownCloud version:

* Go to the https://owncloud.org/install[ownCloud Download Page].
* Go to *Download ownCloud Server > Download > Archive file for server
owners* and download either the tar.bz2 or .zip archive.
* This downloads a file named owncloud-x.y.z.tar.bz2 or
owncloud-x.y.z.zip (where x.y.z is the version number).
* Download its corresponding checksum file, e.g.
owncloud-x.y.z.tar.bz2.md5, or owncloud-x.y.z.tar.bz2.sha256.
* Verify the MD5 or SHA256 sum:
+
....
md5sum -c owncloud-x.y.z.tar.bz2.md5 < owncloud-x.y.z.tar.bz2
sha256sum -c owncloud-x.y.z.tar.bz2.sha256 < owncloud-x.y.z.tar.bz2
md5sum  -c owncloud-x.y.z.zip.md5 < owncloud-x.y.z.zip
sha256sum  -c owncloud-x.y.z.zip.sha256 < owncloud-x.y.z.zip
....
* You may also verify the PGP signature:
+
....
wget https://download.owncloud.org/community/owncloud-x.y.z.tar.bz2.asc
wget https://owncloud.org/owncloud.asc
gpg --import owncloud.asc
gpg --verify owncloud-x.y.z.tar.bz2.asc owncloud-x.y.z.tar.bz2
....
* Now you can extract the archive contents. Run the appropriate
unpacking command for your archive type:
+
....
tar -xjf owncloud-x.y.z.tar.bz2
unzip owncloud-x.y.z.zip
....
* This unpacks to a single `owncloud` directory. Copy the ownCloud
directory to its final destination. When you are running the Apache HTTP
server, you may safely install ownCloud in your Apache document root:
+
....
cp -r owncloud /path/to/webserver/document-root
....
+
where `/path/to/webserver/document-root` is replaced by the document
root of your Web server:
+
....
cp -r owncloud /var/www
....

On other HTTP servers, it is recommended to install ownCloud outside of
the document root.

[[configure-apache-web-server]]
Configure Apache Web Server
---------------------------

On Debian, Ubuntu, and their derivatives, Apache installs with a useful
configuration, so all you have to do is create a
/etc/apache2/sites-available/owncloud.conf file with these lines in it,
replacing the *Directory* and other file paths with your own file paths:

....
Alias /owncloud "/var/www/owncloud/"

<Directory /var/www/owncloud/>
  Options +FollowSymlinks
  AllowOverride All

 <IfModule mod_dav.c>
  Dav off
 </IfModule>

 SetEnv HOME /var/www/owncloud
 SetEnv HTTP_HOME /var/www/owncloud

</Directory>
....

Then create a symlink to /etc/apache2/sites-enabled:

....
ln -s /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf
....

[[additional-apache-configurations]]
Additional Apache Configurations
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* For ownCloud to work correctly, we need the module `mod_rewrite`.
Enable it by running:
+
....
a2enmod rewrite
....
+
Additional recommended modules are `mod_headers`, `mod_env`, `mod_dir`
and `mod_mime`:
+
....
a2enmod headers
a2enmod env
a2enmod dir
a2enmod mime
....
* You must disable any server-configured authentication for ownCloud, as
it uses Basic authentication internally for DAV services. If you have
turned on authentication on a parent folder (via, e.g., an
`AuthType Basic` directive), you can disable the authentication
specifically for the ownCloud entry. Following the above example
configuration file, add the following line in the `<Directory` section
+
....
Satisfy Any
....
* When using SSL, take special note of the `ServerName`. You should
specify one in the server configuration, as well as in the `CommonName`
field of the certificate. If you want your ownCloud to be reachable via
the internet, then set both of these to the domain you want to reach
your ownCloud server.
* Now restart Apache
+
....
service apache2 restart
....
* If you’re running ownCloud in a sub-directory and want to use CalDAV
or CardDAV clients make sure you have configured the correct
service-discovery-label URLs.

[[multi-processing-module-mpm]]
Multi-Processing Module (MPM)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://httpd.apache.org/docs/2.4/mod/prefork.html[Apache prefork] has
to be used. Don’t use a threaded `MPM` like `event` or `worker` with
`mod_php`, because PHP is currently
https://secure.php.net/manual/en/install.unix.apache2.php[not thread
safe].

[[enable-ssl]]
Enable SSL
----------

You can use ownCloud over plain HTTP, but we strongly encourage you to
use SSL/TLS to encrypt all of your server traffic, and to protect user’s
logins and data in transit.

Apache installed under Ubuntu comes already set-up with a simple
self-signed certificate. All you have to do is to enable the `ssl`
module and the default site. Open a terminal and run:

....
a2enmod ssl
a2ensite default-ssl
service apache2 reload
....

Self-signed certificates have their drawbacks - especially when you plan
to make your ownCloud server publicly accessible. You might want to
consider getting a certificate signed by a commercial signing authority.
Check with your domain name registrar or hosting service for good deals
on commercial certificates.

[[run-the-installation-wizard]]
Run the Installation Wizard
---------------------------

After restarting Apache, you must complete your installation by running
either the Graphical Installation Wizard or on the command line with the
`occ` command. To enable this, temporarily change the ownership on your
ownCloud directories to your HTTP user (see strong_perms_label to learn
how to find your HTTP user):

....
chown -R www-data:www-data /var/www/owncloud/
....

Admins of SELinux-enabled distributions may need to write new SELinux
rules to complete their ownCloud installation; see selinux_tips_label.

To use `occ` see command_line_installation. To use the graphical
Installation Wizard see installation_wizard.

Please know that ownCloud’s data directory *must be exclusive to
ownCloud* and not be modified manually by any other process or user.

[[set-strong-directory-permissions]]
Set Strong Directory Permissions
--------------------------------

After completing the installation, you must immediately
set the directory permissions <post_installation_steps_label> in your
ownCloud installation as strictly as possible for stronger security.
After you do so, your ownCloud server will be ready to use.

[[managing-trusted-domains]]
Managing Trusted Domains
------------------------

All URLs used to access your ownCloud server must be whitelisted in your
`config.php` file, under the `trusted_domains` setting. Users are
allowed to log into ownCloud only when they point their browsers to a
URL that is listed in the `trusted_domains` setting.

This setting is important when changing or moving to a new domain name.
You may use IP addresses and domain names.

A typical configuration looks like this:

[source,sourceCode,php]
----
'trusted_domains' => [
   0 => 'localhost', 
   1 => 'server1.example.com', 
   2 => '192.168.1.50',
],
----

The loopback address, `127.0.0.1`, is automatically whitelisted, so as
long as you have access to the physical server you can always log in. In
the event that a load-balancer is in place, there will be no issues as
long as it sends the correct `X-Forwarded-Host` header.

__________________________________________________________________________________________________________________________________
For further information on improving the quality of your ownCloud
installation, please see the configuration_notes_and_tips guide.
__________________________________________________________________________________________________________________________________
