Troubleshooting
===============

This section contains a list of error messages that ownCloud displays
when things go wrong. For each message, you can find the most likely
cause, a resolution, and one or more translations.

[[problem-loading-page-reloading-in-5-seconds]]
Problem loading page, reloading in 5 seconds
--------------------------------------------

[cols=",",]
|=======================================================================
|Cause |

|Resolution |

|Translation |``Problem beim Laden der Seite, Seite wird in 5 Sekunden
nochmals geladen''
|=======================================================================

[[already-existing-files]]
Already existing files
----------------------

[cols=",",]
|=============================================
|Cause |
|Resolution |
|Translation |``Bereits existierende Dateien''
|=============================================

[[which-files-do-you-want-to-keep]]
Which files do you want to keep?"
---------------------------------

[cols=",",]
|=====================================================
|Cause |
|Resolution |
|Translation |``Welche Dateien möchten Sie behalten?''
|=====================================================

[[error-while-sharing]]
Error while sharing
-------------------

[cols=",",]
|====================================
|Cause |
|Resolution |
|Translation |``Fehler beim Teilen'',
|====================================

[[error-while-unsharing]]
Error while unsharing
---------------------

[cols=",",]
|==================================================
|Cause |
|Resolution |
|Translation |``Fehler beim Aufheben der Freigabe''
|==================================================

[[error-while-sending-notification]]
Error while sending notification
--------------------------------

[cols=",",]
|========================================================
|Cause |
|Resolution |
|Translation |``Fehler beim Senden der Benachrichtigung''
|========================================================

[[resharing-is-not-allowed]]
Resharing is not allowed
------------------------

[cols=",",]
|======================================================
|Cause |
|Resolution |
|Translation |``Das Weiterverteilen ist nicht erlaubt''
|======================================================

[[error-removing-share]]
Error removing share
--------------------

[cols=",",]
|===================================================
|Cause |
|Resolution |
|Translation |``Fehler beim Entfernen der Freigabe''
|===================================================

[[internal-server-error]]
Internal Server Error
---------------------

[cols=",",]
|======================================
|Cause |
|Resolution |
|Translation |``Interner Serverfehler''
|======================================

[[this-owncloud-instance-is-currently-in-single-user-mode.]]
This ownCloud instance is currently in single user mode.
--------------------------------------------------------

[cols=",",]
|=======================================================================
|Cause |

|Resolution |

|Translation |``Diese ownClound-Instanz befindet sich derzeit im
Einzelbenutzermodus.''
|=======================================================================

[[this-s-instance-is-currently-in-maintenance-mode-which-may-take-a-while.]]
This %s instance is currently in maintenance mode, which may take a
while.
--------------------------------------------------------------------------

[cols=",",]
|=======================================================================
|Cause |

|Resolution |

|Translation |"Diese %s-Instanz befindet sich gerade im Wartungsmodus,
was eine

| |Weile dauern kann."
|=======================================================================
