External Storage Backends
=========================

This section shows how a standard app can provide external storage
backends.

To do so, requires several steps. These are:

* link:[Configure the filesystem type]
* link:[Implement the storage class(es)]
* link:[Create the backend adapter]
* link:[Register the backend adapter]
* link:[Test the storage backend]

To save time, however, you can learn from an existing example, by
reading through the source code of the
https://github.com/owncloud/files_external_ftp[FTP external storage
app].

[[configure-the-filesystem-type]]
Configure the filesystem type
-----------------------------

First, the /appinfo/info.xml must be adjusted to specify the `type` as:
`filesystem`. For example:

[[implement-the-storage-classes]]
Implement the storage class(es)
-------------------------------

Next, you need to create a storage class. Usually, you should implement
the interface `\\OCP\\Files\\Storage\\IStorage`. But, the easiest way is
to directly extend `\\OCP\\Files\\Storage\\StorageAdapter`, as it
already provides an implementation for many of the commonly required
methods.

Here’s an example of how you would create one that implements all the
filesystem operations required by ownCloud, using a fictitious library
called `FakeStorageLib`.

For this example we mapped the available storage methods to the ones
from the library. Note that, in many cases, the underlying library might
not support some operations and might need extra code to work this
around.

When extending StorageAdapter, it is good practice to implement the
following methods, for performance reasons:

* file_exists
* filetype
* fopen
* getId
* mkdir
* opendir
* rmdir
* stat
* touch
* unlink

If you don’t, your storage backend will still work. But, it will likely
not perform as well as it could. In the case of the `rename` method,
this is because it uses a combination of a stream copy plus a delete for
renaming a file.

[[statmetadata-cache]]
Stat/metadata cache
~~~~~~~~~~~~~~~~~~~

To create a mature implementation, we need to consider stat and metadata
caching. Within a single PHP request, ownCloud might call the same
storage methods repeatedly, due to different checks which it needs to
carry out. As a result, there is the potential to incur significant
overhead, when working with the underlying filesystem.

To avoid — or at the very least _reduce_ this — a stat/metadata cache
should be implemented, if the underlying library does not support
stat/metadata caching. To do this, the metadata of any folder entries
which are read should be cached in a local array and returned by the
storage class’ methods.

[[writing-a-flysystem-adapter]]
Writing a Flysystem adapter
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instead of writing everything by hand, it is also possible to write an
ownCloud adapter based on a
https://flysystem.thephpleague.com/creating-an-adapter/[Flysystem
adapter], as external storage. You can see how it was done in the
https://github.com/owncloud/files_external_ftp/blob/master/lib/Storage/FTP.php#L27[FTP
storage adapter].

[[create-the-backend-adapter]]
Create the backend adapter
--------------------------

After implementing the storage class, a backend adapter needs to be
created. To do that, create a class that extends from
`\\OCP\\Files\\External\\Backend`:

[[definition-parameters]]
Definition parameters
~~~~~~~~~~~~~~~~~~~~~

[[flags]]
Flags:
^^^^^^

[cols=",",options="header",]
|=============================================================
|Flag |Description
|*DefinitionParameter::FLAG_NONE* |No flags (default)
|*DefinitionParameter::FLAG_OPTIONAL* |For optional parameters
|=============================================================

[[types]]
Types:
^^^^^^

[cols=",",options="header",]
|=======================================================================
|Type |Description
|*DefinitionParameter::VALUE_TEXT* |Text field (default)

|*DefinitionParameter::VALUE_PASSWORD* |Masked text field, for passwords
and

| |keys

|*DefinitionParameter::VALUE_BOOLEAN* |Boolean / checkbox

|*DefinitionParameter::VALUE_HIDDEN* |Hidden field, useful with custom

| |scripts
|=======================================================================

[[authentication-schemes]]
Authentication schemes
~~~~~~~~~~~~~~~~~~~~~~

Several authentication schemes can be specified.

[cols=",",options="header",]
|=======================================================================
|Scheme |Description
|*AuthMechanism::SCHEME_NULL* |No authentication supported

|*AuthMechanism::SCHEME_BUILTIN* |Authentication is provided through

| |definition parameters

|*AuthMechanism::SCHEME_PASSWORD* |Support for password-based auth,

| |provides two fields ``user` and

| |``password` to the parameter list

|*AuthMechanism::SCHEME_OAUTH1* |OAuth1, provides fields ``app_key`,

| |``app_secret`, ``token`, ``token_secret`

| |and ``configured`

|*AuthMechanism::SCHEME_OAUTH2* |OAuth2, provides fields ``client_id`,

| |``client_secret`, ``token` and ``configured`

|*AuthMechanism::SCHEME_PUBLICKEY* |Public key, provides fields
``user`,

| |``public_key`, ``private_key`
|=======================================================================

[[custom-user-interface]]
Custom user interface
~~~~~~~~~~~~~~~~~~~~~

When dealing with complex field values or workflows like
https://en.wikipedia.org/wiki/OAuth[OAuth], an application might need to
provide custom JavaScript code to implement such workflow. To add a
custom script, use the following in the backend constructor:

[source,php]
----
$this->addCustomJs('script');
----

This will automatically load the script /js/script.js from the app
folder. The script itself will need to inject events into the external
storage GUI as there is currently no proper public API to do so.

[[register-the-backend-adapter]]
Register the backend adapter
----------------------------

With the backend adapter created, it next needs to be registered. This
can be done in the `Application` class by implementing the
`IBackendProvider` interface, as in the example below:

[source,php]
----
include::examples/storage-backend/OCA/MyStorageApp/AppInfo/Application.php
----

Then in appinfo/app.php instantiate the `Application` class:

[source,php]
----
<?php

  $app = new \OCA\MyStorageApp\AppInfo\Application();
----

[[test-the-storage-backend]]
Test the storage backend
------------------------

Once the steps above are done, you should be able to mount the storage
in the external storage section.
